pool_name: "纳指/科技基金池"
timezone: "Asia/Shanghai"
us_tickers:
  - "AAPL"
  - "MSFT"
  - "NVDA"
  - "AMZN"
  - "META"
  - "GOOGL"
  - "AVGO"
  - "TSLA"
  - "COST"
  - "GOOG"
  - "NQ=F"
dca:
  base_amount: 10
  thresholds:
    crash: -2.0
    crash_hard: -4.0
    bubble: 3.0
funds:
  - code: "006479"
    name: "广发纳斯达克100C"
    role: "Core_Growth"
  - code: "003123"
    name: "建信纳斯达克100C"
    role: "Core_Growth"
  - code: "005121"
    name: "嘉实红利低波C"
    role: "Defensive_Shield"
    watch:
      daily_change_alert: 0.015
  - code: "000198"
    name: "安信宝利债券C"
    role: "Cash_Buffer"
    watch:
      daily_change_alert: 0.005
